### ISSUE TITLE
Various fixes needed to improve installation experience

### ISSUE THREAD

**Issue by nichannah** [OceansAus/access-om2#10]
Thanks to @AndyHoggANU and others for these. 

- the last line in .gitmodules should be a https:// address, otherwise it won’t work for gumbies like myself & Kial who don’t have ssh keys set up. I put an issue on this one in github.
 - get_input_data.py doesn’t work without sh, which has to be installed by the user, and requires python 2.7.11 … would help if that was more generic.
 - making worked well, but we would suggest putting the pytest instructions first, and making it more explicit that there are two ways of doing this.
 - the suggest commands to copy the executables should be “cp” not “ls”. Also, include optional commands for the other resolutions of cice.

**Comment by adele157** [comment]
I was able to follow the installation instructions without issue (seemed to compile fine, still waiting to run). The only thing I noted to change was that the path given in the 'Run' instructions should be:
cd $ACCESS_OM_DIR/control/1deg_jra55_ryf/

**Comment by adele157** [comment]
Also, it would have been useful to know in the 'Run' instructions that access-om2 requires payu/dev, not payu/0.7.

And the naming instructions for the cice executable are for the 1deg model. For the 025 model it would be useful to know that it needs to be: bin/cice_auscom_1440x1080_480p_fa5b0bcf.exe

**Comment by marshallward** [comment]
I can do a payu 0.8 system update today if that helps.  AFAIK payu/dev can only be accessed inside v45.

**Comment by nicjhan** [comment]
* Better documentation about getting the CICE resolution right.

**Comment by nicjhan** [comment]
* It would be good to automate moving/renaming the executables and updating the config.yaml with the correct name. This step would need to:
   1. check the repo HEAD hash
   2. check a hash stored in the exe
   3. do the copy to the right filename (based on the above hashes)
   4. update the config.yaml

**Comment by FanghuaWu** [comment]
Following the installation instructions, I have already run the model. However, when collating the output files, I got the following error message: 

> Traceback (most recent call last):
   File "/jobfs/local/pbs/mom_priv/jobs/7765834.r-man2.SC", line 9, in <module>
    collate_cmd.runscript()
  File "/projects/v45/apps/payu/dev/lib/payu/subcommands/collate_cmd.py", line 98, in runscript
    expt.collate()
  File "/projects/v45/apps/payu/dev/lib/payu/experiment.py", line 625, in collate
    model.collate()
  File "/projects/v45/apps/payu/dev/lib/payu/models/fms.py", line 85, in collate
    assert mppnc_path
AssertionError

According to the suggestion from Aidan, cp `mppnccombine` to $ACCESS_OM_DIR/bin/ and then works.

Do I miss something? Or where to copy `mppnccombine` file should be mentioned in the instructions.

**Comment by AndyHoggANU** [comment]
Hi Fanghua,
No, you didn't miss anything - I had this problem as well and forget to tell Nic when he did the re-release. I agree we should add this to the instructions when we can.

**Comment by aekiss** [comment]
In the course of following these instructions I've also worked on my clone of the instructions (README.md) to address the issues I came across and also deal with those listed here. I'll circulate tomorrow for comment.

**Comment by aekiss** [comment]
Are the build instructions intended to just create JRA versions only or also CORE2?

I found `python -m pytest test/test_build.py` creates `src/matm/build_nt62/matm_nt62.exe` (the CORE2 version) instead of  `src/matm/build_jra55/matm_jra55.exe` so is missing the 1deg JRA.

In contrast, the non-pytest build creates create `$ACCESS_OM_DIR/control/1deg_core_nyf` but does not build the executable `$ACCESS_OM_DIR/src/matm/build_nt62/matm_nt62.exe`

**Comment by aekiss** [comment]
some more things: after going through the compilation 
* `control/025deg_jra55_ryf/ocean/input.nml` needs `io_layout = 6,5` added to the `&ocean_model_nml` group.
* `control/*/ocean/input.nml` need  
```
     debug_this_module=.false.
     riverspread_diffusion=.true.
     riverspread_diffusion_passes = 2
     vel_micom_smooth = 0.2
```
added to `&ocean_riverspread_nml` group.

**Comment by nicjhan** [comment]
Thank you @FanghuaWu and @aekiss this is very useful feedback. Let's plan to do another release soon to incorporate all of these fixes.

**Comment by aekiss** [comment]
OK here's my edit to README.md 
[README.txt](https://github.com/OceansAus/access-om2/files/1233106/README.txt)
(named README.txt as github weirdly won't allow .md upload - should I do this as a pull request instead? - sorry, very new to github!)

I think it covers all the points raised above (other than the first two bullets in the opening post which I didn't really follow and weren't a problem for me) but let me know if I've missed anything. I tried to present it in a way that could be followed by a beginning grad student with basic unix skills but no other experience - but let me know if anything is more confusing than it should be.

A number of points (labelled TODO and BUG) would probably be good to follow up as part of the next release.

I've worked through these instructions (the non-pytest version) to check and have 1deg_jra55 and 025deg_jra queued but I'm yet to see whether they run successfully.

**Comment by aekiss** [comment]
I recently updated README.md with these commits: https://github.com/OceansAus/access-om2/commit/457d2163e266333a07ba2b6ef327e6a21229eb49 https://github.com/OceansAus/access-om2/commit/cab127bb6c7f1e9dbd648d0915321fb2d4079a4b https://github.com/OceansAus/access-om2/commit/350bcfe826bf8fd25b39c3f03ea007995878baeb https://github.com/OceansAus/access-om2/commit/849103f4504903251a0cba3b80cc5cc3ccc76555

However the documentation is still out of date and inconsistent between README.md (https://github.com/OceansAus/access-om2/blob/master/README.md) and the wiki (https://github.com/OceansAus/access-om2/wiki). I think some of us should get together and redesign things to make it clearer and more coordinated. 

Some suggestions:
- [ ] Make README.md into a much briefer overview, with detailed instructions merged and consolidated into the wiki
- [ ] Update wiki, e.g
  - [ ] https://github.com/OceansAus/access-om2/wiki/Basic-Model-Timestepping should use Payu
- [ ] Organise and partition documentation based on the needs of different users, e.g.
  - [ ] brief, clear, simple instructions for new users who want to obtain and analyse output from existing model runs but not do any runs themselves (i.e. a link to the cookbook)
  - [ ] brief, clear, simple instructions for new users who want to run a model without recompiling (but perhaps with changes to diags, namelists, forcing) - e.g. how to spinup or branch from an existing experiment and contribute config (https://github.com/OceansAus/access-om2/wiki/Contributing-to-model-configurations)
  - [ ] detailed, complete instructions for recompiling (i.e. most of what's in existing README.md) for more advanced users
  - [ ] instructions and notes by/for developers to remind us of how to we did things

**Comment by aekiss** [comment]
Looks like the binaries in /short/public/access-om2/bin are incomplete and out of date:
> ls -l /short/public/access-om2/bin/
total 62284
-rwxr-xr-x 1 nah599 v45  7811595 Sep 20 21:45 cice_auscom_3600x2700_1200p_fe730022.exe*
-rwxr-xr-x 1 nah599 v45  7894078 Aug 31 15:02 cice_auscom_360x300_24p_fe730022.exe*
-rwxr-xr-x 1 nah599 v45 38198723 Aug 31 17:35 fms_ACCESS-OM_030fb1f2.x*
-rwxr-xr-x 1 nah599 v45  4884714 Aug 31 15:02 matm_jra55_2318e909.exe*
-rwxr-xr-x 1 nah599 v45  4883056 Sep 12 13:44 matm_nt62_b1f482c3.exe*
-rwxr-xr-x 1 nah599 v45    86952 Aug 31 15:02 mppnccombine*

cice_auscom_1440x1080_480p_fe730022.exe is missing

matm_jra55_2318e909.exe is 4 commits behind current (b1f482c3): https://github.com/OceansAus/matm/commits/master

Ideally /short/public/access-om2/bin should be automatically updated by a script as per #40.

**Comment by aekiss** [comment]
config submodules need better explanation: https://github.com/OceansAus/access-om2/issues/42#issuecomment-346602379

**Comment by nichannah** [comment]
May of the points in this issue have or are being addressed. The conversation is being referenced in the wiki: https://github.com/OceansAus/access-om2/wiki/Getting-started
