### ISSUE TITLE
Red Sea/Gulf Bay salinity fix runtime blowout with increased vertical resolution ACCESS-OM2

### ISSUE THREAD

**Issue by kialstewart** [OceansAus/access-om2#101]
My understanding of increased vertical resolution means you should expect a 1:1 increase in compute time.

This is not what we are getting with the 1 degree; the 50 level cases take ~3.5 hours/decade, while the 135 level case takes closer to 14 hours/decade.

A quick look with @marshallward  revealed the "Red Sea/Gulf Bay salinity fix" function goes from 3409.5 time units per something to 24487.7 (7.2 times longer, rather than 2.7 times longer). Other expensive functions have a >2.7 times increase in compute time (neutral physics is 2.9 times longer, for example), but nothing close to this blowout.

In the 135 level case, almost 50% of the total runtime is spent on this "Red Sea/Gulf Bay salinity fix" versus 25% in the 50 level case (which I feel is too high anyway...?).

Any help with this is much appreciated! @aidanheerdegen

Kial

**Comment by aidanheerdegen** [comment]
The Red Sea/Gulf Bay sailinity fix is a horrible hack and we shouldn't be using it.

Is that helpful?

**Comment by kialstewart** [comment]
Sweet I'll turn it off. Thanks!

**Comment by aidanheerdegen** [comment]
Nah, then the Red Sea will get super saline and your model will crash. What I mean was, we needed to have written something better, but we didn't

**Comment by kialstewart** [comment]
Are we sure that the increased vertical resolution hasn't already achieved the intended purpose of this redsea/gulfbay salinity fix?

**Comment by aidanheerdegen** [comment]
No. I guess we don't know that. Give it a burl then and see what happens.

**Comment by russfiedler** [comment]
If you are running with surface salinity restoring the it probably isn't needed
`! Perform horizontal mixing to fix the Red Sea and Gulf Bay salinity
! drift for ACCESS simulations (no SSS restoring)`

**Comment by marshallward** [comment]
Will CM2 use this?  If so then it probably still ought to be looked into.

**Comment by russfiedler** [comment]
Yes. CM2 requires it. There is insufficient exchange of water with the Indian ocean and salinity builds up.

**Comment by aidanheerdegen** [comment]
Fixed https://github.com/mom-ocean/MOM5/pull/247
