### ISSUE TITLE
losing too much salt - sign of salt flux might be wrong. 

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#13]
It looks like ACCESS-OM2 is losing salt too quickly. On a related matter - although perhaps not a cause  - it looks like the sign of salt flux is wrong in the ocean. See attached from @AndyHoggANU. 

The LH plot is from ACCESS, the RH plot is from MOM-SIS.

<img width="1587" alt="screen shot 2017-07-24 at 2 14 23 pm" src="https://user-images.githubusercontent.com/921706/28508910-88d8be82-7081-11e7-8732-aafd115a2be3.png">

**Comment by nicjhan** [comment]
Hi @russfiedler, you may know something about this. From my investigation it looks like MOM5 assumes that a -ve salt flux is salt entering the ocean, however CICE sees +ve salt flux as entering the ocean. This would explain why the ACCESS-OM2 above is upside-down.

Reference in MOM: https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_sbc.F90#L3502

Reference in CICE: https://github.com/OceansAus/cice5/blob/master/source/ice_therm_vertical.F90#L492
(notice that -ve dhi (ice melting) will lead to increased salt flux).

**Comment by russfiedler** [comment]
@nicjhan  @AndyHoggANU we should be able to see what is happening  from a look at a 2D plot of the salt flux into the ocean due to ice formation/melting in the polar regions. During summer there should be a positive salt flux into the ocean since we are melting slightly salty ice. There should also be a posive water flux into the ocean. I've just had a look at one of Fabio's runs and there's a negative waterflux (diagnostic variable "melt") in January in the Antarctic! The diagnostic sfc_salt_flux_ice is also negative along with sfc_salt_flux_coupler. These are definitely the wrong sign.

**Comment by nicjhan** [comment]
Hi @russfiedler thanks for confirming this. I noticed this is an issue in CICE4 as well. I wonder whether it is in CM. @peterdobro, you may be interested in this.

**Comment by AndyHoggANU** [comment]
Thanks Russ. I had a quick look, but we haven't specifically saved 2D monthly fields of salt flux. We have saved pme_river which seems be positive in the summer, which is what it should be, right?

Nic, maybe the best thing to do here is for me to run another year with extra monthly diagnostics?

**Comment by nicjhan** [comment]
Hi @AndyHoggANU that sounds good. If possible would be good to do the same for MOM+SIS.

@russfiedler ok this is getting a little confusing. Just confirming that Fabio's run is from before I changed melt to use the coupling fields rather than salt flux, https://github.com/mom-ocean/MOM5/pull/176/files (21 Jun 2017). Prior to that melt was -1 * Ice_ocean_boundary%salt_flux(i,j)*ice_salt_concentration_r.

**Comment by russfiedler** [comment]
Hi @nicjhan  @AndyHoggANU  just had a look at Andy's run at /g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf/output050/ocean and the term sfc_salt_flux_coupler =  T_prog(index_salt)%stf(:,:) is definitely the wrong sign. Negative values in the south in January. How should this be handled? CICE, MOM or the coupler? I don't like making hacks to MOM for this sort of thing.  I'd like to hide the scaling in the coupler if possible or put it in CICE.

**Comment by nicjhan** [comment]
Hi @russfiedler, thanks for looking at it. I agree, I don't think it should be put in ocean_sbc.F90. We could put it in the coupler on the MOM side, eg. in: https://github.com/mom-ocean/MOM5/blob/master/src/access_coupler/mom_oasis3_interface.F90 . The advantage of this is that it will apply to both the OM and CM coupled models. If we put it on the ice side then it needs to be put in each CICE driver, i.e. drivers/access and drivers/auscom.

**Comment by russfiedler** [comment]
Yep, that looks like the spot. It's even commented that it's the spot!

! Handle conversions from raw field to what mom requires
! Sign conventions  & scaling  factors. Partioning of SSW etc.

**Comment by nicjhan** [comment]
I've added the fix, see:

https://github.com/mom-ocean/MOM5/commit/f2a120dd67663c7c35e983ffad8e6c0f58af216f

**Comment by AndyHoggANU** [comment]
Hi Both,

Russ, firstly, thanks for looking at my output! I haven't had time yet, but I will look tomorrow to check. For reference, I have just put on the MOM-SIS run that Nic requested. I think this is important to confirm we have nailed the problem.

Nic, am happy to rebuild and rerun, but perhaps you want to wait for other fixes before we do that?

Cheers
Andy

On 25 Jul 2017, at 5:36 pm, Nic Hannah <notifications@github.com<mailto:notifications@github.com>> wrote:


I've added the fix, see:

mom-ocean/MOM5@f2a120d<https://github.com/mom-ocean/MOM5/commit/f2a120dd67663c7c35e983ffad8e6c0f58af216f>

**Comment by AndyHoggANU** [comment]
Hi  @russfiedler, @nicjhan;
I've had time now to look at the MOM-SIS run in comparison with the ACCESS-OM2 run.
The relevant directories are:
/g/data3/hh5/tmp/cosima/mom025/mom025_jra_ryf9091/output101
and
/g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf/output050/
In these you will see that sfc_salt_flux_coupler is the opposite sign. Confusingly to me, sfc_salt_flux_ice is the same sign, but I suspect you both expected that.

I have also checked the first 10 years of the 1 degree ACCESS-OM2 run, which you can find here:
/g/data3/hh5/tmp/cosima/access-om2/1deg_jra55_ryf/
You will see the sign of sfc_salt_flux_coupler is the same as in ACCESS-OM2-025.
