### ISSUE TITLE
CICE -> MOM coupling arrays are set before CICE tilmestep complete

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#18]
In the CICE mainloop the coupling arrays (e.g. salt and water fluxes) are collected in the middle of the ice timestep. i.e. after the first thermo calculations but before second thermo, dynamics and radiation. It's not clear why this has been done because a likely effect is that the coupling arrays have not finished being updated. 

For example fresh() is stored ready for the coupler before CICE has added rain passing through the ice.

This is not the way things work with the other drivers e.g. CESM and ACCESS-CM.

On the other hand step_therm2 starts with a comment:
! Driver for thermodynamic changes not needed for coupling:
! transport in thickness space, lateral growth and melting.
!

**Comment by russfiedler** [comment]
@nicjhan  I totally agree with you on this. I can't understand how the rain which falls on the ice will get through. It looks like Arnold changed the ordering in 2014 but previously rain over ice was added to fresh. Maybe the answer is to change

! 3) rainfall to ocean
  tiorain(:,:,:) = frain(:,:,:) * (1. - aice(:,:,:))

to
! 3) rainfall to ocean
  tiorain(:,:,:) = frain(:,:,:)

This will mean that wiiform and wfimelt will just refer to melting and ice formation terms and rain is really is rain as it should be. Of course if rain gets frozen or something like that and doesn't pass through  then all bets are off.

**Comment by russfiedler** [comment]
Just checked on AusCOM/CICE4. It has the same odd coupling sequence from way back, so it wasn't him who put it there. It was just a backward compatibility thing. @arnoldsu any ideas?

**Comment by russfiedler** [comment]
Ok, Dave Bi has a version where the calls to get_i2o_fluxes and tavg_i2o_fluxes are performed after the call to post_thermo as we would expect. These edits were made on 15/04/2014. i.e. the day after Arnold's compatibility edits. Looks like this issue was recognised and fixed but an old version got ingested here.

**Comment by StephenGriffies** [comment]
Another reason to work through Github!

**Comment by arnoldsu** [comment]
I have loaded Dave's recent (Chen Scheme and coupling reorder) version based on Peter's version. We are still testing. Just bewared that our cice versions are different.

**Comment by ofa001** [comment]
Just finally tracked down the version Russ mentioned where Dave found this problem in CICE5.0.4, it clearly was incorrectly carried over into from someone else's set up CICE5.1.2 and was missed (apologies) its clearly quite suble based on Dave's comments repeated here. This date on Dave's directory I found it in was April 1st 2014 don't think we should read anything into it! 

/short/p66/dhb599/ACCESS-OM/submodels/cice5.0.4 etc


!dhb599: NOTE the change in CICE5 code structure (iblk loop being explicit above),
!        i2o coupling fields need to be handled outside the loop!
!        If, (very possibly), this gives funny results, we need set a temporary
!        array 'recording' the cpl fields for each 'iblk' (just after call to
!        step_thermal as done before) and then do the following handling:

**Comment by nicjhan** [comment]
Hi @ofa001 and @arnoldsu thank you very much for your input on this one! It looks like we're close to finding a solution.

**Comment by ofa001** [comment]
Just been chatting to @arnoldsu about this and we have been tracking this in our svn and how it got on to the github.  My suggestion is one of you tries a new run over the weekend with the April15th 2014 fix of Dave's in the current version. It may not solve all the current problems but may eliminate some of them.

**Comment by nicjhan** [comment]
Hi @ofa001 and @arnoldsu worth noting that the code you have pointed to (/short/p66/dhb599/ACCESS-OM/submodels/cice5.0.4) still doesn't look right. For example the coupling fields are still being read before the ice tilmestep is finished and before coupling_prep() (and others) are called. coupling_prep() does important things such as remove fpond from ffresh. I'd be interested to know if there is a specific reason for this decision. Thanks.

**Comment by nicjhan** [comment]
I have fixed this. There is a clear improvement in the salt balance. I think we agree that there's no convincing reason to send the coupling fields before the CICE tilmestep is finished.
