### ISSUE TITLE
River runoff is too concentrated

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#20]
The 0.25 configuration is crashing near river outflow points. We assume this is to do with high fresh water concentration. 

To fix this we should introduce river spread into the online runoff remapping.

**Comment by nicjhan** [comment]
From @AndyHoggANU

However, it turns out that this is not the spot where the model is crashing — our problem is the amazon — see attached image which shows the offending tile. Here, the runoff is concentrated on a single grid cell — up to 0.4 kg/m^2/s, which I think is even higher than the point Russ was looking at.

<img width="564" alt="screen shot 2017-08-03 at 8 55 30 pm" src="https://user-images.githubusercontent.com/921706/28949805-85a0870c-7902-11e7-9ba5-a34266643914.png">

**Comment by StephenGriffies** [comment]
You may wish to play with the diffusive options in ocean_riverspread.  Here is a first suggestion.  

ocean_riverspread_nml
use_this_module              = .true.
riverspread_diffusion        = .true.
riverspread_diffusion_passes = 2
vel_micom_smooth             = 0.2    

Steve

**Comment by nicjhan** [comment]
Thanks @StephenGriffies.

Also, as part of the online regridding I've implemented a way to set an upper limit on runoff in a cell (in kg/m^2/s). If a value exceeds this it will be distributed to neighbouring cells. 

The question is, what would a good limit be? Do you have any idea @russfiedler? I've looked at @AndyHoggANU regridded runoff at /short/v45/amh157/mom/input/mom025_jra_ryf/RYF.runoff_all.1990_1991.025.nc but the maximum still looks very high.

**Comment by nicjhan** [comment]
The latest MATM (https://github.com/OceansAus/matm/tree/2318e909b07fdbb3a11d81ef9a1d8826e04c2cf8) has the runoff limit functionality described above. Presently it is a compile-time thing set to 0.03 kg/m2/s . I'm leaving this issue open until we make this a runtime config/parameter.

**Comment by aidanheerdegen** [comment]
@nicjhan The runoff file you're referring to was generated by me from Russ' code. The scripts to generate them is here:

/g/data1/ua8/MOM/runoff/JRA55-do/v1-1/regrid_runoff

And there was no spreading. It was all nearest neighbour, so not surprising there are some large values.

**Comment by nicjhan** [comment]
All done in https://github.com/OceansAus/matm/pull/6 thanks @aekiss
