### ISSUE TITLE
The model crashes intermittently 

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#21]
This is a bit of a catch-all issue for all those intermittent model crashes.

Please add a comment below to document any new crashes. Please include:
1. output of:
   ```
   $ cd $ACCESS_OM_DIR
   $ git rev-parse HEAD
   ```
2. the experiment name, e.g. 1deg_jra55_ryf or 025deg_jra55_ryf or 01deg_jra55_ryf
3. the model time when the crash occurred.
4. the error message if you can find one. We expect that many of these will be salt or temp going out of range in the ocean. Output from this error can be found in access-om2.err . In this case please include the geographic location (x, y, z) and model indices (I, j, k) where the out of range value occurs. 
5. the tilmestep
6. thoughts and next steps

**Comment by nicjhan** [comment]
1. 704b4c736a06f6f681d918c5b782d0e3f9a66360
2. 025deg_jra55_ryf
3. idate:     70821
4. FATAL from PE  1421:  Error: temperature out of range with value    -4.643833508984E+01 at (i,j,k) = ( 249,10
56,  9),  (lon,lat,dpt) = ( -259.1545,   83.1888,   87.5301 m)
5. timestep 900s

**Comment by nicjhan** [comment]
Further to the above. The run with ice dynamics ndtd = 2 did not work. It crashed a couple of days later in the same region. 
3.  idate:     70829
4. FATAL from PE  1423:  Error: temperature out of range with value    -3.690281827310E+01 at (i,j,k) = ( 317,10
73, 13),  (lon,lat,dpt) = ( -262.0558,   87.4533,  134.8414 m)

**Comment by nicjhan** [comment]
== 0.1 deg crash related to ice model transport/advection ==

1. 704b4c736a06f6f681d918c5b782d0e3f9a66360
2. 01deg_jra55_ryf
3. idate:     40209
4. remap transport: bad departure points
5. timestep 400s
6. I think this error indicates that ice is moving too fast. It seems to be moving at roughly the same speed as the ocean in some areas such as the coast of Greenland.

**Comment by ofa001** [comment]
Hi Nic, we put a limit on the speed of the ice (5m/s ) as the model got very fast early in the coupled spin up. Both off Greenland and in the North pacific in grid boxes with tiny fractions of ice.  The other time step to adjust in the early stage of spin up  is the ndte ( I guess you are looking at page 73 of the Cice5.1 manual).  
My Adelaide ice wave colleague just suggesting  using access-om2-025 for our work (even without a wave scheme) I told hi  it was still in progress but an option. I'll definitely  point him to these :)

**Comment by ofa001** [comment]
4.remap transport: bad departure points
5.timestep 400s
6.I think this error indicates that ice is moving too fast. It seems to be moving at roughly the same speed as the ocean in some areas such as the coast of Greenland.

There is code in ice_dyn_shared.F90 in our coupled set up to stop this you will find it in the link Peter gave you but its here.

#ifdef AusCOM
!20160624 -- Siobhan and Dave's idea to set ice velocity limit to avoid
!transport remap "departure point error":
         !if (abs(uvel(i,j) >= vel_max) uvel(i,j) = sign(c1, uvel(i,j))
         !* vel_max
         !if (abs(vvel(i,j) >= vel_max) vvel(i,j) = sign(c1, vvel(i,j))
         !* vel_max
         uvel(i,j) = sign(min(abs(uvel(i,j)),vel_max),uvel(i,j))
         vvel(i,j) = sign(min(abs(vvel(i,j)),vel_max),vvel(i,j))
#endif

**Comment by AndyHoggANU** [comment]
1. c4209361
2. 025deg_jra55_ryf
3. idate:     61010
4. FATAL from PE  1446:  Error: salinity out of range with value    -1.323328814906E+01 at (i,j,k) = (1125,1080, 15),  (lon,lat,dpt) = (   78.7923,   87.5229,  163.9870 m)
5. timestep: 600 seconds. I managed to get to year 5 using 300 second timesteps; crash occurs 18 months after increasing back up to 600.
6. Again, crash occurs in regions where ice shows waviness. Here is u_vel from CICe in the month before the crashed (iceh_09):
<img width="289" alt="screen shot 2017-08-20 at 4 28 42 pm" src="https://user-images.githubusercontent.com/26753100/29492613-cae22086-85c4-11e7-9404-470cecc5d45c.png">

next step here is to use massless ice for this model. Will investigate this during the week.

**Comment by aekiss** [comment]
re. massless ice - I've completed 1 year of 025deg_jra55_ryf with massless ice (`max_ice_thickness=0.0`) and 540s timestep. No obvious problems so I've submitted a continuation for another 4 years.

**Comment by nicjhan** [comment]
I think this approach holds promise. My run has not crashed at dt = 900s with this setting. They waves are still there but reduced after one year. Now trying 1200 s.

**Comment by nicjhan** [comment]
The dt = 1200s runs did not crash, now trying dt = 1800.

**Comment by aekiss** [comment]
We will make mass conservation worse with max_ice_thickness=0.0 but presumably that's the lesser of two evils?
https://github.com/mom-ocean/MOM5/blob/f6f4e4ae7f0fb966b0e2ba8fc33ae0caa96950a2/src/mom5/ocean_core/ocean_sbc.F90#L307
```
!  <DATA NAME="max_ice_thickness" UNITS="m" TYPE="real">
!  When coupling MOM to an ice model, the sea ice thickness may need
!  to be restricted to prevent vanishing top-level in MOM. Set 
!  max_ice_thickness (meters) < dzt(k=1) to restrict. This truncation 
!  avoids the numerical problem but we loose mass conservation in the coupled
!  sea ice and ocean system. We also alter the pressure felt on the ocean 
!  as applied by the sea ice. Different vertical coordinates are needed 
!  to do the problem more realistically.   
!
!  Note that the problem of vanishing top layer is removed when use
!  either ZSTAR or PSTAR as vertical coordinate.  
!  </DATA> 
```

**Comment by StephenGriffies** [comment]
I wrote this comment in the code.  But I do not recall where mass conservation is broken.  

We routinely use the max_ice_thickness option with it sometimes set to 5m and sometimes to 0m. But there is no spurious mass loss/gain.  One can verify the mass conservation by examining the output of fms.out where we print mass conservation diagnostics.  Comparing max_ice_thickness=0 versus max_ice_thickness=5 should reveal no systematic differences.  

We routinely run our coupled atmosphere/ocean models with zero mass atmosphere felt by the ocean. Yet there is mass conserved between the atmosphere and ocean when rain/evap occurs.  

I will try to recollect why I wrote that code comment years ago. But at this point I see no worries about mass conservation.

**Comment by AndyHoggANU** [comment]
1. 1fe26731
2.  1deg_jra55_ryf 
3. MATM istep1:     12919    idate:     71120    sec:         0
4. FATAL from PE   175:  Error: salinity out of range with value     5.537461166799E+01 at (i,j,k) = ( 112, 247,  5),  (lon,lat,dpt) = ( -168.4919,   65.6404,   45.1490 m)
5. 2160
6. This is a simulation which should be able to run faster, but I'm struggling to push it beyond 1800 seconds. I tested the timestep on 1deg_jra_ryf_spinup8, and we concluded that we probably needed massless ice. But this is occurring in the Bering Strait, I think, in October when there is no ice, so I'm no longer convinced this is the problem ...

**Comment by AndyHoggANU** [comment]
An update on my last post. I ran the 1deg_jra_ryf case for another 8 years at 1800 seconds, then switched back up to 2160. The crash happens with salinity out of range in exactly the same place. We need to be able to do better than this, so will invest more time in investigating.

**Comment by nicjhan** [comment]
This issues has been useful for documenting and solving two problems:

1. the need for massless ice
2. high velocities in the Bering Strait

In future we should keep the issues more self contained, i.e. create a separate issue for every crash.
