### ISSUE TITLE
MOM and CICE create too many log files 

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#26]
Presently MOM and CICE create a log file for each PE. This is too much and blows out the inode quota on raijin after a short time when we are on high resolution.

**Comment by russfiedler** [comment]
Looks like MOM doesn't even write to the files apart from the root node.

**Comment by marshallward** [comment]
That is my understanding too.  Is this about the OASIS log output?

**Comment by russfiedler** [comment]
Yes, those are the culprits. See mom_oasis3_interface.F90. The initial opening of the fields can be restricted to the root PE. Doesn't look like the files are closed properly either. The CICE files can probably be eliminated except for debugging purposes (maybe).

**Comment by ofa001** [comment]
Most of the CICE debug output doesn't go in those individual process files it goes into the ice_diag.d and ice_diag_out.  
The iceoutxx files are tracking the passing back and forth by oasisMCT of the coupling fields and which time step its for. If it fails you know which time step, that's about all you can find from the iceoutxx's

**Comment by russfiedler** [comment]
True. But there's no need to keep them unless there's an error. The files can then opened and written to as needed. Alternatively, if there are no problems with the run then they can be closed and deleted automatically with`close(il_out,status='DELETE')`.

**Comment by ofa001** [comment]
That could be an option for both the ocean and ice ones, I will chat to Dave and see if has any input on it, At the moment he is re-working coupling order due to reproducibility issues so for tests like that they could be useful. But filling up disc is definitely a problem for us looking ahead to CMIP6 runs so cutting down on runtime output will help.

**Comment by ofa001** [comment]
Dave mentions that there is a housekeeping option in cylc-run that will clean up the all but the last 4 lower level  4 "time level" input directories" that will prevent too much of this type output building up during the production runs.

**Comment by nicjhan** [comment]
I've taken the approach of only having verbose output during DEBUG runs. For a production run these files are not created. Future work could include cleaning up how output is done in DEBUG, e.g. we probably never want one file per PE.

**Comment by aekiss** [comment]
The sync scripts in the new configurations now delete all 105-character `ice.log.task_*` files, as these contain the heading only. See e.g. https://github.com/COSIMA/01deg_jra55_iaf/commit/84a41e89d8f4bfb46ea548ef7ad9860dc6f9f339
