### ISSUE TITLE
CICE injecting a lot of salt into ocean

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#27]
The fsalt variable in CICE (visible as diagnostic fsalt_ai_m) does not appear to be balanced over time. A lot more salt is entering the ocean than leaving. I'm not yet sure whether this is coming from the NH or SH. One possible explanation is that the model has started with too much ice in the NH and it is melting.

**Comment by ofa001** [comment]
Fsalt_ai  patterns look almost identical in pattern to the “melt” patterns plotted out by the ocean model (though there appeared to be  a scaling factor involved). As you weren’t loosing all the summer ice in the SH (like we are unfortunately are in the coupled case you may also be building up ice mass in the SH over a long run).
Initially on start up they will unlikely be in balance as the model is set up with a  latitudinal dependent ice cover which is not in balance with the CORE atmospheric forcing fluxes.

I will have a look is this in the 1 degree run I guess it is as the 0.25 was faulty.

Siobhan

**Comment by nicjhan** [comment]
Thanks @ofa001, this is happening in the 1 deg. I'll post a path for you to take a look once it's finished copying.

**Comment by ofa001** [comment]
Hi @nicjhan I think its the NH ice adjusting through the adjustment from mid way through your current run to the end year 86 is more settled in terms of salt fluxes and ice volumes. In the initial stages it is adjusting from the artificial ice distribution set up which is set up latitudinally  to  one which has thicker ice on the Greenland and Canadian side of the Arctic. It does actually loose ice as it exits through Fram St too the Greenland Sea,  so melt more than accrete though most of the melt is outside the central basin. 

I haven't made an time series as your files are buried at low levels of directories, I guess the "cookbook" will eventually do so.

**Comment by nicjhan** [comment]
This problem has improved a lot since https://github.com/OceansAus/access-om2/issues/18 was fixed. This is no longer a problem.
