### ISSUE TITLE
Check units and ranges for forcing fields

### ISSUE THREAD

**Issue by nichannah** [OceansAus/access-om2#38]
Strange things happen when forcing fields are in wrong/unexpected units. It can take a long time to find these problems, for example the confusion we had when we switched the CORE to JRA55 runoff fields and the units changed. 

It would save a lot of time in the long run if we did some sanity checking on incoming fields. In this case of MATM this could be done without any hit to overall performance (because it does nothing most of the time anyway).

**Comment by ofa001** [comment]
Its possible we might want to use some CFSR forcing fields as well to match a CFSR wave climatology that Mark Hemer created that myself and Luke Bennetts have used with the old accice set up.

We are going to have some discussions this week about whether we switch to using COSIMA and meet with other groups in the UK doing wave-ice interaction.
Luke’s been here for a couple of weeks so been talking already, I caught a cold on the plane over so been less sociable.

**Comment by nichannah** [comment]
Moved to https://github.com/OceansAus/libaccessom2/issues/9
