### ISSUE TITLE
Ice restarts are accumulating

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#44]
This is more of a payu issue I think. It looks like the ice restarts are accumulating in the restart directory. This means there will be many copies of the same restart. For example take a look at:

/g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf_spinup7/restart055/ice

As part of this fix we should also delete all of the duplicate restarts that must exist in hh5.

**Comment by nicjhan** [comment]
This is the command I used to clean mine up: 

[nah599@raijin4 archive]$ pwd
/short/e14/nah599/access-om2/control/1deg_jra55_ryf/archive
[nah599@raijin4 archive]$ for f in $(ls -d restart*); do cd $f/ice/; restart=$(cat ice.restart_file | cut -d '/' -f 3); find . -name 'iced.*.nc' -not -name $restart -delete; cd -; done

Us with caution!

**Comment by marshallward** [comment]
Nic can you set up an example somewhere for me to look at?  I'm on leave and won't get a chance for a while

**Comment by nicjhan** [comment]
This is fixed in https://github.com/marshallward/payu/pull/86

**Comment by marshallward** [comment]
Nevermind!

**Comment by nicjhan** [comment]
Fixed now but let's leave the issue open until @aekiss and @AndyHoggANU have fixed their runs in hh5.

**Comment by aekiss** [comment]
Thanks for spotting this and fixing payu Nic. 
Will this new payu be made available as a module? 
At present I'm loading payu/0.8a as previous versions don't support access-om2 -- should I use payu/dev instead?

**Comment by marshallward** [comment]
I can update 0.8a now.

**Comment by marshallward** [comment]
Actually... 0.8 is more or less finished, maybe I could just do a full update and set 0.8 as default?

**Comment by aekiss** [comment]
sure, whatever works best for you

**Comment by marshallward** [comment]
I've updated 0.8a with the newest changes (including github sync and archived error logs).

If it works OK for you without any problems then I'll do a full 0.8 update.

**Comment by aekiss** [comment]
Thanks @marshallward, the new payu/0.8a works for me. It removes the earliest ice restart when it adds a new one - so they don't accumulate, but if there's a long list of redundant restarts between the earliest and latest these are not removed so I used @nicjhan's script to tidy up the excess restarts.

**Comment by marshallward** [comment]
@aekiss @nicjhan I am not really following this issue with ice restarts; are you saying there is more work to do / could be done on this issue?  Or is it OK to do a release?

**Comment by aekiss** [comment]
OK to do a release - this fixes the ice restart accumulation problem.

I was only noting that runs that had already accumulated extra ice restarts would not have them cleared away by payu. This can be fixed by Nic's script (2nd post above) and will not be a problem in future.

**Comment by AndyHoggANU** [comment]
It may fix the ice restart files accumulation bug. But I'm not sure that it fixes our other bug, which is that some restarts set the ice and MATM time back to day 1, while ocean time keeps incrementing. Mind you, I don't know if that is an ACCESS-OM2 bug or a payu bug ...

**Comment by marshallward** [comment]
You mean #43 right?  If so, can this issue be closed?  Maybe also tag #43 with payu if necessary?

**Comment by ofa001** [comment]
It should probably be checked in the latest set up under our approach.  I guess Arnold may be busy at the moment as Dave is about to travel overseas and I am still there.

Does seem like Payu creates a lot of extra files for you though. lots of interesting stuff to report back on the future sea ice models  (2020’s era)I return!

Cheers
Siobhan
