### ISSUE TITLE
Write test to check submodel start times

### ISSUE THREAD

**Issue by nichannah** [OceansAus/access-om2#46]
This test would look through the model output and check that all models are starting at the correct / same time. 

Inspired by #43

**Comment by nicjhan** [comment]
The MOM output looks like this: 

 ==>Note: Time%Time_init = time stamp at very start of the MOM experiment is given by
yyyy/mm/dd hh:mm:ss =    1/ 1/ 1  0: 0: 0

 ==>Note: Time%model_time = time stamp at start of this leg of the MOM experiment is
yyyy/mm/dd hh:mm:ss =   19/ 1/ 1  0: 0: 0

MATM looks like this: 

MATM (init_calendar) idate0 =        10101
MATM istep1:        47    idate:     10102    sec:         0

CICE looks like this in ice_diag.d:

istep1:         0    idate:     10101    sec:         0

**Comment by nicjhan** [comment]
This test should not only include model start times but also forcing and restart data times. 

This test relates to this issue:

https://github.com/OceansAus/access-om2/issues/70

**Comment by nichannah** [comment]
This is no longer relevant since libaccessom2 because it sets all start times. It also checks all model end times.
