### ISSUE TITLE
Remove unused input files

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#47]
There are quite a few files in the ACCESS-OM2 test case input dataset which I suspect are unused. 

For example access-om2/input/mom_025deg/ includes things like ncar_precip.nc, near_rad.nc. Are these needed?

**Comment by ofa001** [comment]
@nicjhan  These files are part of the old set up using ncar data, so probably not relevant to the boundary layer set up options now being used.

Tried to put this through the web interface but it wouldn’t let me, despite accepting my password etc. Siobhan
