### ISSUE TITLE
CICE unnecessarily calls HaloUpdate on coupling fields immediately after receiving them

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#53]
Each CICE PE does a halo update on each coupling field between atm and ocean immediately after receiving these from OASIS. These are expensive, e.g. for a 20 day 0.1 deg run ice_diag.d says:

Timer  23: ocn_halos    1772.89 seconds
  Timer stats (node): min =        0.33 seconds
                      max =     1772.89 seconds
                      mean=      420.71 seconds

Timer  24: atm_halos      21.78 seconds
  Timer stats (node): min =        0.01 seconds
                      max =       21.78 seconds
                      mean=        6.68 seconds

These are absolute values from a run with runtime 8444.737558 s. The reason that the ocean coupling field halos are using so much more time than the atmosphere if because the ice and ocean couple more frequently. 

There is no obvious reason why halo updates should be necessary if OASIS is configured properly. The halos should be filled in by the coupler, not with a separate call afterwards. 

A fix for this issue will figure our how OASIS can fill the halos of the coupling fields and remove all of these calls to HaloUpdate in the CICE driver code. This will improve the code and should have a noticeable effect on 0.1 deg performance.

**Comment by russfiedler** [comment]
Hmm... I really don't agree with this at all. The coupler should be completely independent of things that are internal to the models like halos. Also, this completely breaks the 1 to 1 mapping of the LOCTRANS mapping.

Also are you sure that this sort of synchronisation wouldn't happen anyway and you're just seeing it here.

**Comment by russfiedler** [comment]
@nicjhan  Hi, I'm convinced this is a general synchonisation issue which is certain to happen no matter what. Have a look at /g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf_spinup7/output149/ice/ice_diag.d 

Timer  23: ocn_halos      30.59 seconds
  Timer stats (node): min =        0.23 seconds
                      max =       30.59 seconds
                      mean=       13.58 second

That's tiny. But


Timer  17:  from_ocn    2641.91 seconds
  Timer stats (node): min =        2.91 seconds
                      max =     2641.91 seconds
                      mean=      356.41 seconds
  Timer stats(block): min =        0.00 seconds
                      max =        0.00 seconds
                      mean=        0.00 seconds
Timer  18: waiting_o    2637.95 seconds
  Timer stats (node): min =        0.63 seconds
                      max =     2637.95 seconds
                      mean=      348.44 seconds


I think all that will happen is that the problem will just be pushed to the next halo update in the main ice code. The real key is to find the optimal processor number/layout mix. It's a tough job though.

**Comment by russfiedler** [comment]
Just putting a placeholder here. Nic is going to add a barrier just before the ocn_halos timer to see if it's a synchronization problem or if the updating of the halos is the culprit.

**Comment by nicjhan** [comment]
Thanks for your input @russfiedler . You've convinced me that the coupler shouldn't get involved with halo updates. I'll look further into your suggestions re. synchronisation.
