### ISSUE TITLE
Create CORE2 IAF experiments

### ISSUE THREAD

**Issue by nichannah** [OceansAus/access-om2#64]
Create and test CORE2 IAF experiments at all resolutions. 

Fabio has done these runs in the past, so it is expected that the code will not need to be changed much.

**Comment by fabiobdias** [comment]
Thanks @nicjhan 

I'm using a single netcdf file with all CORE2 IAF years (1948-2007) to each forcing variable. The MATM is facing a problem in the remap_runoff_mod.F90 (line 290) when comparing source/destination integrals:

   > ! Compare the above.
   > rel_err = abs(src_total - dst_total) / src_total

Any ideas on this?

**Comment by nicjhan** [comment]
Thanks @fabiobdias, glad to hear that you're running this. Yes, the way that runoff is handled has changed a bit. It now uses the runoff provided on the atmosphere grid. Can you point me to your where your data_4_matm.table and atmospheric forcing files are?

**Comment by fabiobdias** [comment]
Hi @nicjhan The data_4_matm.table is at /home/581/fbd581/payu/access-om2_core-iaf/atmosphere/. It is using a runoff locate at /short/v45/fbd581/access-om2/input/core_iaf_all/runoff.nc which is basically the /g/data1/v45/mom/core2iaf/runoff.nc with dimensions/variables names modified from (grid_x_T, grid_y_T, Time) to (longitude, latitude, time).
