### ISSUE TITLE
Header metadata in input files

### ISSUE THREAD

**Issue by PaulSpence** [OceansAus/access-om2#68]
Hi Folks,

Apologies, I know there is a lot to do, but in the long run I think it is import to include more header metadata in some of the input files:

For example, 

ncdump -h access-om2/input/mom_025deg/ocean_temp_salt.res.nc

should include the source of the temp and salt data (e.g. WOA13). This is important legacy info.

Thank you,
Paul

**Comment by aekiss** [comment]
I agree. We are discussing this sort of thing in https://github.com/OceansAus/access-om2/issues/57 so I've moved your comment there and will close this issue. See https://github.com/OceansAus/access-om2/issues/57 for followup to your comment.
