### ISSUE TITLE
install.sh reports success even if MOM build fails

### ISSUE THREAD

**Issue by marshallward** [OceansAus/access-om2#81]
When running `install.sh`: 
If the MOM build fails, it prints some errors but happily moves on and scrolls far past these errors, reporting "Success" at the end.

This may be true of the other models as well.

**Comment by aekiss** [comment]
I've updated install.sh to remove existing executables before compiling and then check whether all executables exist after compiling, failing with error if any are missing. I think this addresses this issue.
