### ISSUE TITLE
ice and ocean lagging the atmosphere

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#84]
Currently the first ice (ocean) timestep is forced by the prior atmospheric forcing. This can be seen by comparing the shortwave field in i2o.nc to the first time point in a forcing dataset. 

The reason this happens is that the namcouple uses the LAG setting between the atmosphere and ice. From the oasis manual: 

"If a coupling field has a positive lag, the coupling field that matches the oasis get at time=0 will come from a coupling restart file written by the last active oasis put of the previous run."

I don't see any reason for this lag in the ACCESS-OM model. It complicates the system (using LAG in namcouple and needing an extra restart file). Furthermore, at restart time it means that the ice model is forced by the ocean model one timestep prior (e.g. 450s, 2700s, 5400s) but the atmosphere model 10800s prior (granted the ocean itself has been forced by atmos 10800s prior).  

Really all it means is that the whole system is running 3 hours behind where it says it is. If there is no convincing argument to keep doing things this way I suggest we change it.  

There is some related discussion in this issue: https://github.com/OceansAus/access-om2/issues/82

**Comment by ofa001** [comment]
Hi nicjhan as I said to Russ a coupe of weeks ago Dave Hailin (now at BOm) and Arnold rewrote our coupler set up for stand alone ice -ocean 6 months ago we were tracking down reproducibility issues if you are going to re-work  this one I would talk to them first.  Dave is away until after Easter. I alerted him to your renewed interest when he was last in

There has always been a lag built into the system the atmosphere has always led as you need that data to drive the other components it was 6 hrs at 1 deg but less in coupled system, so could be reduced at .1 degree as well if you have higher frequency data available.

**Comment by nicjhan** [comment]
This has been fixed by YATM and libaccesom2
