### ISSUE TITLE
MOM website update

### ISSUE THREAD

**Issue by aekiss** [OceansAus/access-om2#94]
Just so we don't forget:

On Thu, Jun 22, 2017 at 10:12 PM, Stephen Griffies wrote:
Group,

I was going through the mom-ocean.science web site and have some suggestions for updates.

--It seems time to remove all mention of Breakaway Labs. It is mentioned at the top of the page as well as the link to the Model Development Lab.  

--The COSIMA web site has a link to the mom-ocean.science web site, which is great.  I suggest that mom-ocean.science should reciprocate.  Perhaps there could be an "announcement" to point to the COSIMA project and its use/release of MOM5 based configurations.  Should I presume you wish to have these configurations used by others outside of COSIMA?   

Part of me wishes to get exposure to COSIMA among the MOM community.  I also wish to let the MOM community know that there are still ongoing activities. The most recent update on mom-ocean.science was made 28 Nov, 2015 when we released the Southern Ocean visualization.  We should let the MOM community know about ongoing work.  

--We should provide a pointer from mom-ocean.science to the ENSO visualization from mom-ocean.science.  This is another opportunity for an announcement on mom-ocean.science to let the community know there is stuff happening.  

--  Please update the MOM history document with this one
https://drive.google.com/open?id=0ByuYBnZYpSJBMnVPUjZJS0xlMW8

**Comment by aidanheerdegen** [comment]
Good idea, but maybe best as an issue on the MOM5 repo?

**Comment by aekiss** [comment]
done: https://github.com/mom-ocean/MOM5/issues/222
